sudo: required
dist: trusty
addons:
  sonarqube: true
jdk:
  - openjdk11
before_install: 
  - chmod +x travis.sh
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
  - sudo apt-get update
  - sudo apt-get install mono-complete mono-devel dos2unix
  - wget -O os.deb http://oscript.io/downloads/night-build/deb
  - sudo dpkg -i os.deb; sudo apt install -f
  - oscript
install:  
  - sudo opm install 
  - sudo opm install 1testrunner
  - sudo opm install v8runner
  - sudo opm install readparams
  - sudo opm install yadisk
  - sudo opm install cmdline
  - sudo opm install moskito
  - sudo opm list
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
script: 
  - ./travis.sh